version: '3'

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: ./flask_app
    environment:
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_ACCESS_KEY: ${AWS_SECRET_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
      X_OCR_SECRET: ${X_OCR_SECRET}
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 wsgi:server
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - flask_app