name: ci-cd-pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Generate Environment Variables File
        run: |
          touch .env
          echo "AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}" >> .env
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          echo "X_OCR_SECRET=${{ secrets.X_OCR_SECRET }}" >> .env
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Github Action IP 가져오기
      - name: get Github Actions IP
        id: ip
        uses: haythem/public-ip@v1.3

      # AWS IAM for EC2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_EC2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_EC2_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # EC2 보안그룹에 현재 ip 추가
      - name: Add Github Actions IP to Security Group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_EC2_SG_ID }} --protocol tcp --port 22 --cidr ${{steps.ip.outputs.ipv4 }}/32

      # # yml 파일 ec2에 복사
      # - name: Copy File via ssh password
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ubuntu
      #     key: ${{ secrets.KEY }}
      #     port: 22
      #     source: "docker-compose.yml"
      #     target: "/home/ubuntu"

      # ec2에 디렉토리 생성
      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: mkdir -p /home/ubuntu/src/clova

      # ec2에 소스코드 복사
      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/src/clova/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.PRIVATE_KEY }}


      # EC2 접속 & 서버 올리기
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.6
        # env:
        #   AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        #   AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        #   BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        #   X_OCR_SECRET: ${{ secrets.X_OCR_SECRET }}
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          # envs: 
          #   AWS_ACCESS_KEY,AWS_SECRET_KEY,BUCKET_NAME,X_OCR_SECRET
          script: |
            echo "my aws's bucket_name is ${{ secrets.BUCKET_NAME }}"
            export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            export AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            export BUCKET_NAME=${{ secrets.BUCKET_NAME }}
            export X_OCR_SECRET=${{ secrets.X_OCR_SECRET }}
            sh /home/ubuntu/src/clova/run_docker.sh

      # - name: define secrets injected to docker
      #   run: |
      #     docker swarm init
      #     printf ${{ secrets.AWS_ACCESS_KEY }} | docker secret create AWS_ACCESS_KEY -
      #     printf ${{ secrets.AWS_SECRET_KEY }} | docker secret create AWS_SECRET_KEY -
      #     printf ${{ secrets.BUCKET_NAME }} | docker secret create BUCKET_NAME -
      #     printf ${{ secrets.X_OCR_SECRET }} | docker secret create X_OCR_SECRET -


      # - name: Docker-compose up
      #   uses: isbang/compose-action@v1.4.1
      #   with:
      #     compose-file: "./docker-compose.yml"
      #     up-flags: "--build"
      #   env:
      #     AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      #     AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      #     BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      #     X_OCR_SECRET: ${{ secrets.X_OCR_SECRET }}

      # EC2 보안그룹에서 추가한 ip 삭제
      - name: Remove Github Actions IP from Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_EC2_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4}}/32
